// <copyright file="SignatureVerificationResult.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Types.Sdk;
using System.Linq;

namespace WebhooksAndCallbacksAPI.Standard.Events
{
    /// <summary>
    /// Represents the result of an operation that can either succeed
    /// or fail with an error message.
    /// </summary>
    public sealed class SignatureVerificationResult : VerificationResult
    {
        internal SignatureVerificationResult(VerificationResult result)
            : base(result.Errors?.ToArray())
        {
        }
    }

    internal static class SignatureVerificationResultExtensions
    {
        public static SignatureVerificationResult ToSignatureVerificationResult(this VerificationResult  result)
        {
            return new SignatureVerificationResult(result);
        }
    }
}