// <copyright file="EventType2.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace WebhooksAndCallbacksAPI.Standard.Models
{
    /// <summary>
    /// EventType2.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum EventType2
    {
        /// <summary>
        /// EnumPrimitivevariant.
        /// </summary>
        [EnumMember(Value = "primitive.variant")]
        EnumPrimitivevariant
    }
}