// <copyright file="Event.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace WebhooksAndCallbacksAPI.Standard.Models
{
    /// <summary>
    /// Event.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Event
    {
        /// <summary>
        /// EnumOrdercreated.
        /// </summary>
        [EnumMember(Value = "order.created")]
        EnumOrdercreated,

        /// <summary>
        /// EnumOrderupdated.
        /// </summary>
        [EnumMember(Value = "order.updated")]
        EnumOrderupdated,

        /// <summary>
        /// EnumOrdercancelled.
        /// </summary>
        [EnumMember(Value = "order.cancelled")]
        EnumOrdercancelled,

        /// <summary>
        /// EnumPaymentcompleted.
        /// </summary>
        [EnumMember(Value = "payment.completed")]
        EnumPaymentcompleted,

        /// <summary>
        /// EnumPaymentfailed.
        /// </summary>
        [EnumMember(Value = "payment.failed")]
        EnumPaymentfailed,

        /// <summary>
        /// EnumFulfillmentcompleted.
        /// </summary>
        [EnumMember(Value = "fulfillment.completed")]
        EnumFulfillmentcompleted
    }
}