// <copyright file="FulfillmentStatuss.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace WebhooksAndCallbacksAPI.Standard.Models
{
    /// <summary>
    /// FulfillmentStatuss.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum FulfillmentStatuss
    {
        /// <summary>
        /// Fulfilled.
        /// </summary>
        [EnumMember(Value = "fulfilled")]
        Fulfilled,

        /// <summary>
        /// Failed.
        /// </summary>
        [EnumMember(Value = "failed")]
        Failed,

        /// <summary>
        /// Partial.
        /// </summary>
        [EnumMember(Value = "partial")]
        Partial
    }
}