// <copyright file="FulfillmentCallback.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using WebhooksAndCallbacksAPI.Standard.Models.Containers;
using WebhooksAndCallbacksAPI.Standard.Utilities;

namespace WebhooksAndCallbacksAPI.Standard.Models
{
    /// <summary>
    /// FulfillmentCallback.
    /// </summary>
    public class FulfillmentCallback
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string trackingNumber;
        private List<Models.OauthScopeOauthACG> scopes;
        private string notes;
        private string orderIdd;
        private string trackingNumberr;
        private List<Models.OauthScopeOauthACG> scopess;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "trackingNumber", false },
            { "scopes", false },
            { "notes", false },
            { "orderIdd", false },
            { "trackingNumberr", false },
            { "scopess", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentCallback"/> class.
        /// </summary>
        public FulfillmentCallback()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentCallback"/> class.
        /// </summary>
        /// <param name="fulfillmentStatus">fulfillmentStatus.</param>
        /// <param name="orderId">orderId.</param>
        /// <param name="trackingNumber">trackingNumber.</param>
        /// <param name="carrier">carrier.</param>
        /// <param name="scopes">scopes.</param>
        /// <param name="estimatedDelivery">estimatedDelivery.</param>
        /// <param name="timestamp">timestamp.</param>
        /// <param name="document">document.</param>
        /// <param name="totalWeight">totalWeight.</param>
        /// <param name="price">price.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="longId">longId.</param>
        /// <param name="fragile">fragile.</param>
        /// <param name="notes">notes.</param>
        /// <param name="items">items.</param>
        /// <param name="packages">packages.</param>
        /// <param name="address">address.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="attributes">attributes.</param>
        /// <param name="deliveryDetails">deliveryDetails.</param>
        /// <param name="orderIdd">orderIdd.</param>
        /// <param name="fulfillmentStatuss">fulfillmentStatuss.</param>
        /// <param name="trackingNumberr">trackingNumberr.</param>
        /// <param name="carrierr">carrierr.</param>
        /// <param name="scopess">scopess.</param>
        /// <param name="estimatedDeliveryy">estimatedDeliveryy.</param>
        /// <param name="timestampp">timestampp.</param>
        /// <param name="documentt">documentt.</param>
        public FulfillmentCallback(
            Models.FulfillmentStatus fulfillmentStatus,
            string orderId = null,
            string trackingNumber = null,
            string carrier = null,
            List<Models.OauthScopeOauthACG> scopes = null,
            DateTime? estimatedDelivery = null,
            DateTime? timestamp = null,
            Stream document = null,
            double? totalWeight = null,
            double? price = null,
            int? quantity = null,
            long? longId = null,
            bool? fragile = null,
            string notes = null,
            List<string> items = null,
            List<Models.Package> packages = null,
            Models.Address address = null,
            object metadata = null,
            Dictionary<string, string> attributes = null,
            FulfillmentCallbackDeliveryDetails deliveryDetails = null,
            string orderIdd = null,
            Models.FulfillmentStatuss? fulfillmentStatuss = null,
            string trackingNumberr = null,
            string carrierr = null,
            List<Models.OauthScopeOauthACG> scopess = null,
            DateTime? estimatedDeliveryy = null,
            DateTime? timestampp = null,
            Stream documentt = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.OrderId = orderId;
            this.FulfillmentStatus = fulfillmentStatus;

            if (trackingNumber != null)
            {
                this.TrackingNumber = trackingNumber;
            }
            this.Carrier = carrier;

            if (scopes != null)
            {
                this.Scopes = scopes;
            }
            this.EstimatedDelivery = estimatedDelivery;
            this.Timestamp = timestamp;
            this.Document = document;
            this.TotalWeight = totalWeight;
            this.Price = price;
            this.Quantity = quantity;
            this.LongId = longId;
            this.Fragile = fragile;

            if (notes != null)
            {
                this.Notes = notes;
            }
            this.Items = items;
            this.Packages = packages;
            this.Address = address;
            this.Metadata = metadata;
            this.Attributes = attributes;
            this.DeliveryDetails = deliveryDetails;

            if (orderIdd != null)
            {
                this.OrderIdd = orderIdd;
            }
            this.FulfillmentStatuss = fulfillmentStatuss;

            if (trackingNumberr != null)
            {
                this.TrackingNumberr = trackingNumberr;
            }
            this.Carrierr = carrierr;

            if (scopess != null)
            {
                this.Scopess = scopess;
            }
            this.EstimatedDeliveryy = estimatedDeliveryy;
            this.Timestampp = timestampp;
            this.Documentt = documentt;
        }

        /// <summary>
        /// Gets or sets OrderId.
        /// </summary>
        [JsonProperty("orderId", NullValueHandling = NullValueHandling.Include)]
        public string OrderId { get; set; }

        /// <summary>
        /// Gets or sets FulfillmentStatus.
        /// </summary>
        [JsonProperty("fulfillmentStatus")]
        public Models.FulfillmentStatus FulfillmentStatus { get; set; }

        /// <summary>
        /// Gets or sets TrackingNumber.
        /// </summary>
        [JsonProperty("trackingNumber")]
        public string TrackingNumber
        {
            get
            {
                return this.trackingNumber;
            }

            set
            {
                this.shouldSerialize["trackingNumber"] = true;
                this.trackingNumber = value;
            }
        }

        /// <summary>
        /// Gets or sets Carrier.
        /// </summary>
        [JsonProperty("carrier", NullValueHandling = NullValueHandling.Ignore)]
        public string Carrier { get; set; }

        /// <summary>
        /// List of scopes that apply to the OAuth token
        /// </summary>
        [JsonProperty("scopes")]
        public List<Models.OauthScopeOauthACG> Scopes
        {
            get
            {
                return this.scopes;
            }

            set
            {
                this.shouldSerialize["scopes"] = true;
                this.scopes = value;
            }
        }

        /// <summary>
        /// Gets or sets EstimatedDelivery.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("estimatedDelivery", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? EstimatedDelivery { get; set; }

        /// <summary>
        /// Gets or sets Timestamp.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// Binary file upload
        /// </summary>
        [JsonProperty("document", NullValueHandling = NullValueHandling.Ignore)]
        public Stream Document { get; set; }

        /// <summary>
        /// Gets or sets TotalWeight.
        /// </summary>
        [JsonProperty("totalWeight", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalWeight { get; set; }

        /// <summary>
        /// Gets or sets Price.
        /// </summary>
        [JsonProperty("price", NullValueHandling = NullValueHandling.Ignore)]
        public double? Price { get; set; }

        /// <summary>
        /// Gets or sets Quantity.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Ignore)]
        public int? Quantity { get; set; }

        /// <summary>
        /// Gets or sets LongId.
        /// </summary>
        [JsonProperty("longId", NullValueHandling = NullValueHandling.Ignore)]
        public long? LongId { get; set; }

        /// <summary>
        /// Gets or sets Fragile.
        /// </summary>
        [JsonProperty("fragile", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Fragile { get; set; }

        /// <summary>
        /// Explicitly nullable field
        /// </summary>
        [JsonProperty("notes")]
        public string Notes
        {
            get
            {
                return this.notes;
            }

            set
            {
                this.shouldSerialize["notes"] = true;
                this.notes = value;
            }
        }

        /// <summary>
        /// Gets or sets Items.
        /// </summary>
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Items { get; set; }

        /// <summary>
        /// Gets or sets Packages.
        /// </summary>
        [JsonProperty("packages", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.Package> Packages { get; set; }

        /// <summary>
        /// Gets or sets Address.
        /// </summary>
        [JsonProperty("address", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Address Address { get; set; }

        /// <summary>
        /// Gets or sets Metadata.
        /// </summary>
        [JsonProperty("metadata", NullValueHandling = NullValueHandling.Ignore)]
        public object Metadata { get; set; }

        /// <summary>
        /// Gets or sets Attributes.
        /// </summary>
        [JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
        public Dictionary<string, string> Attributes { get; set; }

        /// <summary>
        /// Gets or sets DeliveryDetails.
        /// </summary>
        [JsonProperty("deliveryDetails", NullValueHandling = NullValueHandling.Ignore)]
        public FulfillmentCallbackDeliveryDetails DeliveryDetails { get; set; }

        /// <summary>
        /// Gets or sets OrderIdd.
        /// </summary>
        [JsonProperty("orderIdd")]
        public string OrderIdd
        {
            get
            {
                return this.orderIdd;
            }

            set
            {
                this.shouldSerialize["orderIdd"] = true;
                this.orderIdd = value;
            }
        }

        /// <summary>
        /// Gets or sets FulfillmentStatuss.
        /// </summary>
        [JsonProperty("fulfillmentStatuss", NullValueHandling = NullValueHandling.Ignore)]
        public Models.FulfillmentStatuss? FulfillmentStatuss { get; set; }

        /// <summary>
        /// Gets or sets TrackingNumberr.
        /// </summary>
        [JsonProperty("trackingNumberr")]
        public string TrackingNumberr
        {
            get
            {
                return this.trackingNumberr;
            }

            set
            {
                this.shouldSerialize["trackingNumberr"] = true;
                this.trackingNumberr = value;
            }
        }

        /// <summary>
        /// Gets or sets Carrierr.
        /// </summary>
        [JsonProperty("carrierr", NullValueHandling = NullValueHandling.Ignore)]
        public string Carrierr { get; set; }

        /// <summary>
        /// List of scopes that apply to the OAuth token
        /// </summary>
        [JsonProperty("scopess")]
        public List<Models.OauthScopeOauthACG> Scopess
        {
            get
            {
                return this.scopess;
            }

            set
            {
                this.shouldSerialize["scopess"] = true;
                this.scopess = value;
            }
        }

        /// <summary>
        /// Gets or sets EstimatedDeliveryy.
        /// </summary>
        [JsonConverter(typeof(CustomDateTimeConverter), "yyyy'-'MM'-'dd")]
        [JsonProperty("estimatedDeliveryy", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? EstimatedDeliveryy { get; set; }

        /// <summary>
        /// Gets or sets Timestampp.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("timestampp", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? Timestampp { get; set; }

        /// <summary>
        /// Binary file upload
        /// </summary>
        [JsonProperty("documentt", NullValueHandling = NullValueHandling.Ignore)]
        public Stream Documentt { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FulfillmentCallback : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTrackingNumber()
        {
            this.shouldSerialize["trackingNumber"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetScopes()
        {
            this.shouldSerialize["scopes"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetNotes()
        {
            this.shouldSerialize["notes"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetOrderIdd()
        {
            this.shouldSerialize["orderIdd"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTrackingNumberr()
        {
            this.shouldSerialize["trackingNumberr"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetScopess()
        {
            this.shouldSerialize["scopess"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTrackingNumber()
        {
            return this.shouldSerialize["trackingNumber"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeScopes()
        {
            return this.shouldSerialize["scopes"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeNotes()
        {
            return this.shouldSerialize["notes"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeOrderIdd()
        {
            return this.shouldSerialize["orderIdd"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTrackingNumberr()
        {
            return this.shouldSerialize["trackingNumberr"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeScopess()
        {
            return this.shouldSerialize["scopess"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"OrderId = {this.OrderId ?? "null"}");
            toStringOutput.Add($"FulfillmentStatus = {this.FulfillmentStatus}");
            toStringOutput.Add($"TrackingNumber = {this.TrackingNumber ?? "null"}");
            toStringOutput.Add($"Carrier = {this.Carrier ?? "null"}");
            toStringOutput.Add($"Scopes = {(this.Scopes == null ? "null" : $"[{string.Join(", ", this.Scopes)} ]")}");
            toStringOutput.Add($"EstimatedDelivery = {(this.EstimatedDelivery == null ? "null" : this.EstimatedDelivery.ToString())}");
            toStringOutput.Add($"Timestamp = {(this.Timestamp == null ? "null" : this.Timestamp.ToString())}");
            toStringOutput.Add($"Document = {(this.Document == null ? "null" : this.Document.ToString())}");
            toStringOutput.Add($"TotalWeight = {(this.TotalWeight == null ? "null" : this.TotalWeight.ToString())}");
            toStringOutput.Add($"Price = {(this.Price == null ? "null" : this.Price.ToString())}");
            toStringOutput.Add($"Quantity = {(this.Quantity == null ? "null" : this.Quantity.ToString())}");
            toStringOutput.Add($"LongId = {(this.LongId == null ? "null" : this.LongId.ToString())}");
            toStringOutput.Add($"Fragile = {(this.Fragile == null ? "null" : this.Fragile.ToString())}");
            toStringOutput.Add($"Notes = {this.Notes ?? "null"}");
            toStringOutput.Add($"Items = {(this.Items == null ? "null" : $"[{string.Join(", ", this.Items)} ]")}");
            toStringOutput.Add($"Packages = {(this.Packages == null ? "null" : $"[{string.Join(", ", this.Packages)} ]")}");
            toStringOutput.Add($"Address = {(this.Address == null ? "null" : this.Address.ToString())}");
            toStringOutput.Add($"Metadata = {(this.Metadata == null ? "null" : this.Metadata.ToString())}");
            toStringOutput.Add($"Attributes = {(this.Attributes == null ? "null" : this.Attributes.ToString())}");
            toStringOutput.Add($"DeliveryDetails = {(this.DeliveryDetails == null ? "null" : this.DeliveryDetails.ToString())}");
            toStringOutput.Add($"OrderIdd = {this.OrderIdd ?? "null"}");
            toStringOutput.Add($"FulfillmentStatuss = {(this.FulfillmentStatuss == null ? "null" : this.FulfillmentStatuss.ToString())}");
            toStringOutput.Add($"TrackingNumberr = {this.TrackingNumberr ?? "null"}");
            toStringOutput.Add($"Carrierr = {this.Carrierr ?? "null"}");
            toStringOutput.Add($"Scopess = {(this.Scopess == null ? "null" : $"[{string.Join(", ", this.Scopess)} ]")}");
            toStringOutput.Add($"EstimatedDeliveryy = {(this.EstimatedDeliveryy == null ? "null" : this.EstimatedDeliveryy.ToString())}");
            toStringOutput.Add($"Timestampp = {(this.Timestampp == null ? "null" : this.Timestampp.ToString())}");
            toStringOutput.Add($"Documentt = {(this.Documentt == null ? "null" : this.Documentt.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}