// <copyright file="RootLevelPrimitiveOneOfEventRequest.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace WebhooksAndCallbacksAPI.Standard.Models
{
    /// <summary>
    /// RootLevelPrimitiveOneOfEventRequest.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RootLevelPrimitiveOneOfEventRequest
    {
        /// <summary>
        /// On.
        /// </summary>
        [EnumMember(Value = "on")]
        On,

        /// <summary>
        /// Off.
        /// </summary>
        [EnumMember(Value = "off")]
        Off,

        /// <summary>
        /// Pending.
        /// </summary>
        [EnumMember(Value = "pending")]
        Pending
    }
}