// <copyright file="RootLevelPrimitiveOneOfEventRequest1.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace WebhooksAndCallbacksAPI.Standard.Models
{
    /// <summary>
    /// RootLevelPrimitiveOneOfEventRequest1.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum RootLevelPrimitiveOneOfEventRequest1
    {
        /// <summary>
        /// Alpha.
        /// </summary>
        [EnumMember(Value = "alpha")]
        Alpha,

        /// <summary>
        /// Beta.
        /// </summary>
        [EnumMember(Value = "beta")]
        Beta,

        /// <summary>
        /// Gamma.
        /// </summary>
        [EnumMember(Value = "gamma")]
        Gamma
    }
}