// <copyright file="Status1.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace WebhooksAndCallbacksAPI.Standard.Models
{
    /// <summary>
    /// Status1.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status1
    {
        /// <summary>
        /// Sent.
        /// </summary>
        [EnumMember(Value = "sent")]
        Sent,

        /// <summary>
        /// Failed.
        /// </summary>
        [EnumMember(Value = "failed")]
        Failed
    }
}