// <copyright file="ApiKeyManager.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using APIMatic.Core.Authentication;

namespace WebhooksAndCallbacksAPI.Standard.Authentication
{
    /// <summary>
    /// ApiKeyManager Class.
    /// </summary>
    internal class ApiKeyManager : AuthManager, IApiKeyCredentials
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiKeyManager"/> class.
        /// </summary>
        /// <param name="apiKeyModel">ApiKeyModel.</param>
        public ApiKeyManager(ApiKeyModel apiKeyModel)
        {
            XAPIKey = apiKeyModel?.XAPIKey;
            Parameters(paramBuilder => paramBuilder
                .Header(header => header.Setup("X-API-Key", XAPIKey).Required())
            );
        }

        /// <summary>
        /// Gets string value for xAPIKey.
        /// </summary>
        public string XAPIKey { get; }

        /// <summary>
        /// Check if credentials match.
        /// </summary>
        /// <param name="xAPIKey"> The string value for credentials.</param>
        /// <returns> True if credentials matched.</returns>
        public bool Equals(string xAPIKey)
        {
            return xAPIKey.Equals(this.XAPIKey);
        }
    }

    public sealed class ApiKeyModel
    {
        internal ApiKeyModel()
        {
        }

        internal string XAPIKey { get; set; }

        /// <summary>
        /// Creates an object of the ApiKeyModel using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            return new Builder(XAPIKey);
        }

        /// <summary>
        /// Builder class for ApiKeyModel.
        /// </summary>
        public class Builder
        {
            private string xAPIKey;

            public Builder(string xAPIKey)
            {
                this.xAPIKey = xAPIKey ?? throw new ArgumentNullException(nameof(xAPIKey));
            }

            /// <summary>
            /// Sets XAPIKey.
            /// </summary>
            /// <param name="xAPIKey">XAPIKey.</param>
            /// <returns>Builder.</returns>
            public Builder XAPIKey(string xAPIKey)
            {
                this.xAPIKey = xAPIKey ?? throw new ArgumentNullException(nameof(xAPIKey));
                return this;
            }

            /// <summary>
            /// Creates an object of the ApiKeyModel using the values provided for the builder.
            /// </summary>
            /// <returns>ApiKeyModel.</returns>
            public ApiKeyModel Build()
            {
                return new ApiKeyModel()
                {
                    XAPIKey = this.xAPIKey
                };
            }
        }

        internal static ApiKeyModel FromOptions(ApiKeyModelOptions options)
        {
            var builder = new Builder(options.XAPIKey);
            return builder.Build();
        }
    }

    public class ApiKeyModelOptions
    {
        public string XAPIKey { get; set; }
    }
    
}