// <copyright file="IApiKeyCredentials.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>

namespace WebhooksAndCallbacksAPI.Standard.Authentication
{
    /// <summary>
    /// Authentication configuration interface for ApiKey.
    /// </summary>
    public interface IApiKeyCredentials
    {
        /// <summary>
        /// Gets string value for xAPIKey.
        /// </summary>
        string XAPIKey { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="xAPIKey"> The string value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string xAPIKey);
    }
}