// <copyright file="PetController.cs" company="APIMatic">
// SwaggerPetstore.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using SwaggerPetstore.Standard.Exceptions;
using SwaggerPetstore.Standard.Http.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SwaggerPetstore.Standard.Controllers
{
    /// <summary>
    /// PetController.
    /// </summary>
    public class PetController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PetController"/> class.
        /// </summary>
        internal PetController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Returns a single pet.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet to return.</param>
        /// <returns>Returns the Models.Pet response from the API call.</returns>
        public Models.Pet GetPetById(
                long petId)
            => CoreHelper.RunTask(GetPetByIdAsync(petId));

        /// <summary>
        /// Returns a single pet.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet to return.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.Pet response from the API call.</returns>
        public async Task<Models.Pet> GetPetByIdAsync(
                long petId,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Pet>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/pet/{petId}")
                  .WithAuth("api_key")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("petId", petId))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid ID supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Pet not found", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Updates a pet in the store with form data.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet that needs to be updated.</param>
        /// <param name="contentType">Required parameter: Example: .</param>
        /// <param name="name">Optional parameter: Updated name of the pet.</param>
        /// <param name="status">Optional parameter: Updated status of the pet.</param>
        public void UpdatePetWithForm(
                long petId,
                Models.ContentTypeEnum contentType,
                string name = null,
                string status = null)
            => CoreHelper.RunVoidTask(UpdatePetWithFormAsync(petId, contentType, name, status));

        /// <summary>
        /// Updates a pet in the store with form data.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet that needs to be updated.</param>
        /// <param name="contentType">Required parameter: Example: .</param>
        /// <param name="name">Optional parameter: Updated name of the pet.</param>
        /// <param name="status">Optional parameter: Updated status of the pet.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task UpdatePetWithFormAsync(
                long petId,
                Models.ContentTypeEnum contentType,
                string name = null,
                string status = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/pet/{petId}")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("petId", petId))
                      .Header(header => header.Setup("Content-Type", CoreHelper.JsonSerialize(contentType).Trim('\"')))
                      .Form(form => form.Setup("name", name))
                      .Form(form => form.Setup("status", status))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("405", CreateErrorCase("Invalid input", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Deletes a pet.
        /// </summary>
        /// <param name="petId">Required parameter: Pet id to delete.</param>
        /// <param name="apiKey">Optional parameter: Example: .</param>
        public void DeletePet(
                long petId,
                string apiKey = null)
            => CoreHelper.RunVoidTask(DeletePetAsync(petId, apiKey));

        /// <summary>
        /// Deletes a pet.
        /// </summary>
        /// <param name="petId">Required parameter: Pet id to delete.</param>
        /// <param name="apiKey">Optional parameter: Example: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task DeletePetAsync(
                long petId,
                string apiKey = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Delete, "/pet/{petId}")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("petId", petId))
                      .Header(header => header.Setup("api_key", apiKey))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid ID supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Pet not found", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Add a new pet to the store.
        /// </summary>
        /// <param name="body">Required parameter: Pet object that needs to be added to the store.</param>
        public void AddPet(
                Models.PetRequest body)
            => CoreHelper.RunVoidTask(AddPetAsync(body));

        /// <summary>
        /// Add a new pet to the store.
        /// </summary>
        /// <param name="body">Required parameter: Pet object that needs to be added to the store.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task AddPetAsync(
                Models.PetRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/pet")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("405", CreateErrorCase("Invalid input", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Update an existing pet.
        /// </summary>
        /// <param name="body">Required parameter: Pet object that needs to be added to the store.</param>
        public void UpdatePet(
                Models.PetRequest body)
            => CoreHelper.RunVoidTask(UpdatePetAsync(body));

        /// <summary>
        /// Update an existing pet.
        /// </summary>
        /// <param name="body">Required parameter: Pet object that needs to be added to the store.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task UpdatePetAsync(
                Models.PetRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Put, "/pet")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid ID supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("Pet not found", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("405", CreateErrorCase("Validation exception", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Multiple status values can be provided with comma separated strings.
        /// </summary>
        /// <param name="status">Required parameter: Status values that need to be considered for filter.</param>
        /// <returns>Returns the List of Models.Pet response from the API call.</returns>
        public List<Models.Pet> FindPetsByStatus(
                List<Models.Status2Enum> status)
            => CoreHelper.RunTask(FindPetsByStatusAsync(status));

        /// <summary>
        /// Multiple status values can be provided with comma separated strings.
        /// </summary>
        /// <param name="status">Required parameter: Status values that need to be considered for filter.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the List of Models.Pet response from the API call.</returns>
        public async Task<List<Models.Pet>> FindPetsByStatusAsync(
                List<Models.Status2Enum> status,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<List<Models.Pet>>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/pet/findByStatus")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("status", status?.Select(a => CoreHelper.JsonSerialize(a).Trim('\"')).ToList()))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid status value", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// uploads an image.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet to update.</param>
        /// <param name="additionalMetadata">Optional parameter: Additional data to pass to server.</param>
        /// <param name="file">Optional parameter: file to upload.</param>
        /// <returns>Returns the Models.ApiResponse response from the API call.</returns>
        public Models.ApiResponse UploadFile(
                long petId,
                string additionalMetadata = null,
                FileStreamInfo file = null)
            => CoreHelper.RunTask(UploadFileAsync(petId, additionalMetadata, file));

        /// <summary>
        /// uploads an image.
        /// </summary>
        /// <param name="petId">Required parameter: ID of pet to update.</param>
        /// <param name="additionalMetadata">Optional parameter: Additional data to pass to server.</param>
        /// <param name="file">Optional parameter: file to upload.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.ApiResponse response from the API call.</returns>
        public async Task<Models.ApiResponse> UploadFileAsync(
                long petId,
                string additionalMetadata = null,
                FileStreamInfo file = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ApiResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/pet/{petId}/uploadImage")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("petId", petId))
                      .Form(form => form.Setup("additionalMetadata", additionalMetadata))
                      .Form(form => form.Setup("file", file))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
        /// </summary>
        /// <param name="tags">Required parameter: Tags to filter by.</param>
        /// <returns>Returns the List of Models.Pet response from the API call.</returns>
        [Obsolete]
        public List<Models.Pet> FindPetsByTags(
                List<string> tags)
            => CoreHelper.RunTask(FindPetsByTagsAsync(tags));

        /// <summary>
        /// Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
        /// </summary>
        /// <param name="tags">Required parameter: Tags to filter by.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the List of Models.Pet response from the API call.</returns>
        [Obsolete]
        public async Task<List<Models.Pet>> FindPetsByTagsAsync(
                List<string> tags,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<List<Models.Pet>>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/pet/findByTags")
                  .WithAuth("petstore_auth")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("tags", tags))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid tag value", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}