// <copyright file="UserController.cs" company="APIMatic">
// SwaggerPetstore.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using SwaggerPetstore.Standard.Exceptions;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

namespace SwaggerPetstore.Standard.Controllers
{
    /// <summary>
    /// UserController.
    /// </summary>
    public class UserController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserController"/> class.
        /// </summary>
        internal UserController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Creates list of users with given input array.
        /// </summary>
        /// <param name="body">Required parameter: List of user object.</param>
        public void CreateUsersWithListInput(
                List<Models.User> body)
            => CoreHelper.RunVoidTask(CreateUsersWithListInputAsync(body));

        /// <summary>
        /// Creates list of users with given input array.
        /// </summary>
        /// <param name="body">Required parameter: List of user object.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task CreateUsersWithListInputAsync(
                List<Models.User> body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/user/createWithList")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Get user by user name.
        /// </summary>
        /// <param name="username">Required parameter: The name that needs to be fetched. Use user1 for testing..</param>
        /// <returns>Returns the Models.User response from the API call.</returns>
        public Models.User GetUserByName(
                string username)
            => CoreHelper.RunTask(GetUserByNameAsync(username));

        /// <summary>
        /// Get user by user name.
        /// </summary>
        /// <param name="username">Required parameter: The name that needs to be fetched. Use user1 for testing..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the Models.User response from the API call.</returns>
        public async Task<Models.User> GetUserByNameAsync(
                string username,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.User>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/user/{username}")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("username", username))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid username supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("User not found", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="username">Required parameter: name that need to be updated.</param>
        /// <param name="body">Required parameter: Updated user object.</param>
        public void UpdateUser(
                string username,
                Models.UserRequest body)
            => CoreHelper.RunVoidTask(UpdateUserAsync(username, body));

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="username">Required parameter: name that need to be updated.</param>
        /// <param name="body">Required parameter: Updated user object.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task UpdateUserAsync(
                string username,
                Models.UserRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Put, "/user/{username}")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Template(template => template.Setup("username", username))
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid user supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("User not found", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="username">Required parameter: The name that needs to be deleted.</param>
        public void DeleteUser(
                string username)
            => CoreHelper.RunVoidTask(DeleteUserAsync(username));

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="username">Required parameter: The name that needs to be deleted.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task DeleteUserAsync(
                string username,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Delete, "/user/{username}")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("username", username))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid username supplied", (errorReason, context) => new ApiException(errorReason, context)))
                  .ErrorCase("404", CreateErrorCase("User not found", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Logs out current logged in user session.
        /// </summary>
        public void LogoutUser()
            => CoreHelper.RunVoidTask(LogoutUserAsync());

        /// <summary>
        /// Logs out current logged in user session.
        /// </summary>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task LogoutUserAsync(CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/user/logout"))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="body">Required parameter: Created user object.</param>
        public void CreateUser(
                Models.UserRequest body)
            => CoreHelper.RunVoidTask(CreateUserAsync(body));

        /// <summary>
        /// This can only be done by the logged in user.
        /// </summary>
        /// <param name="body">Required parameter: Created user object.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task CreateUserAsync(
                Models.UserRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/user")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Creates list of users with given input array.
        /// </summary>
        /// <param name="body">Required parameter: List of user object.</param>
        public void CreateUsersWithArrayInput(
                List<Models.User> body)
            => CoreHelper.RunVoidTask(CreateUsersWithArrayInputAsync(body));

        /// <summary>
        /// Creates list of users with given input array.
        /// </summary>
        /// <param name="body">Required parameter: List of user object.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task CreateUsersWithArrayInputAsync(
                List<Models.User> body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/user/createWithArray")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body))
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Logs user into the system.
        /// </summary>
        /// <param name="username">Required parameter: The user name for login.</param>
        /// <param name="password">Required parameter: The password for login in clear text.</param>
        /// <returns>Returns the string response from the API call.</returns>
        public string LoginUser(
                string username,
                string password)
            => CoreHelper.RunTask(LoginUserAsync(username, password));

        /// <summary>
        /// Logs user into the system.
        /// </summary>
        /// <param name="username">Required parameter: The user name for login.</param>
        /// <param name="password">Required parameter: The password for login in clear text.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the string response from the API call.</returns>
        public async Task<string> LoginUserAsync(
                string username,
                string password,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<string>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/user/login")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("username", username))
                      .Query(query => query.Setup("password", password))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid username/password supplied", (errorReason, context) => new ApiException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}