// <copyright file="IApiKeyCredentials.cs" company="APIMatic">
// SwaggerPetstore.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;

namespace SwaggerPetstore.Standard.Authentication
{
    /// <summary>
    /// Authentication configuration interface for ApiKey.
    /// </summary>
    public interface IApiKeyCredentials
    {
        /// <summary>
        /// Gets string value for apiKey.
        /// </summary>
        string ApiKey { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="apiKey"> The string value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string apiKey);
    }
}