// <copyright file="OrdersApi.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using WebhooksAndCallbacksAPI.Standard.Exceptions;
using WebhooksAndCallbacksAPI.Standard.Http.Response;

namespace WebhooksAndCallbacksAPI.Standard.Apis
{
    /// <summary>
    /// OrdersApi.
    /// </summary>
    public class OrdersApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrdersApi"/> class.
        /// </summary>
        internal OrdersApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Creates a new order and triggers callbacks for payment processing.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.Order response from the API call.</returns>
        public ApiResponse<Models.Order> CreateOrder(
                Models.CreateOrderRequest body)
            => CoreHelper.RunTask(CreateOrderAsync(body));

        /// <summary>
        /// Creates a new order and triggers callbacks for payment processing.
        /// </summary>
        /// <param name="body">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Order response from the API call.</returns>
        public async Task<ApiResponse<Models.Order>> CreateOrderAsync(
                Models.CreateOrderRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Order>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/orders")
                  .WithOrAuth(orAuth => orAuth
                      .Add("ApiKey")
                      .Add("BearerAuth")
                  )
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("Invalid request", (errorReason, context) => new ErrorException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}