// <copyright file="CallbacksBHandler.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Http.Abstractions;
using APIMatic.Core.Security.Abstractions;
using APIMatic.Core.Security.SignatureVerifier;
using APIMatic.Core.Types;
using APIMatic.Core.Types.Sdk;
using APIMatic.Core.Types.Sdk.Exceptions;
using APIMatic.Core.Utilities.Json;
using Newtonsoft.Json;
using System;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using WebhooksAndCallbacksAPI.Standard.Http.Request;

namespace WebhooksAndCallbacksAPI.Standard.Events.Callbacks
{
   /// <summary>
   /// Manages CallbacksB event processing, including signature verification and event payload parsing.
   /// </summary>
   public class CallbacksBHandler
   {
       private ISignatureVerifier SignatureVerifier { get; }

       private static Func<IHttpRequestData, CancellationToken, Task<byte[]>> RequestSignatureTemplateResolverAsync =>
           async (request, ct) =>
           {
               if (request == null) throw new ArgumentNullException(nameof(request));

                var payload = await request.ReadBodyAsStringAsync(ct).ConfigureAwait(false) ?? string.Empty;
                var notificationType = string.IsNullOrEmpty(payload)
                    ? string.Empty
                    : JsonPointerResolver.ResolveJsonValue("#/notificationType", payload);

                var result = $"{notificationType}";

                return Encoding.UTF8.GetBytes(result);
           };

        /// <summary>
        /// Initializes a new instance of the <see cref="CallbacksBHandler"/> class with the specified secret key.
        /// </summary>
        /// <param name="secretKey">The secret key used for HMAC signature verification.</param>
        public CallbacksBHandler(string secretKey)
        {
            SignatureVerifier = new HmacSignatureVerifier(secretKey,
                "X-Signature",
                EncodingType.Hex,
                RequestSignatureTemplateResolverAsync,
                HmacAlgorithm.Sha256,
                "{digest}");
        }

        /// <summary>
        /// Verifies the request signature and parses the event payload.
        /// Throws exceptions if signature verification or payload validation fails.
        /// </summary>
        /// <param name="request">The HTTP request data containing the event payload and headers.</param>
        /// <param name="cancellationToken">Token to cancel the operation.</param>
        /// <returns>
        /// or a <see cref="CallbacksBParsingResult.Unknown"/> if parsing fails.
        /// </returns>
        public async Task<CallbacksBParsingResult> VerifyAndParseEventAsync(HttpRequestData request,
            CancellationToken cancellationToken = default)
        {
            var httpRequestData = await request.WithBufferedBody(cancellationToken).ConfigureAwait(false);
            var result = await VerifyAsync(httpRequestData, cancellationToken).ConfigureAwait(false);

            if (!result.IsSuccess)
                return new CallbacksBParsingResult.SignatureVerificationFailed(result);

            var payload = await request.ReadBodyAsStringAsync(cancellationToken).ConfigureAwait(false);
            if (string.IsNullOrEmpty(payload))
                return new CallbacksBParsingResult.Unknown();

            var settings = new JsonSerializerSettings
            {
                MissingMemberHandling = MissingMemberHandling.Error
            };

            try
            {
                return JsonConvert.DeserializeObject<CallbacksBParsingResult>(payload, settings);
            }
            catch (OneOfValidationException)
            {
                return new CallbacksBParsingResult.Unknown();
            }
        }

        /// <summary>
        /// Verifies the request using the configured signature verifier.
        /// Returns a <see cref="SignatureVerificationResult"/> indicating success or failure.
        /// </summary>
        /// <param name="request">The HTTP request data to verify.</param>
        /// <param name="cancellationToken">Token to cancel the operation.</param>
        /// <returns>
        /// A <see cref="SignatureVerificationResult"/> representing the outcome of signature verification.
        /// </returns>
        public async Task<SignatureVerificationResult> VerifyAsync(HttpRequestData request,
            CancellationToken cancellationToken = default)
        {
            return (await SignatureVerifier.VerifyAsync(request, cancellationToken).ConfigureAwait(false))
                .ToSignatureVerificationResult();
        }
    }
}