// <copyright file="CallbacksAParsingResult.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using WebhooksAndCallbacksAPI.Standard.Models;

namespace WebhooksAndCallbacksAPI.Standard.Events.Callbacks
{
    /// <summary>
    /// This is an event class for CallbacksAParsingResult.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<CallbacksAParsingResult>),
        new[] {
            typeof(PaymentCallbackCase),
            typeof(FulfillmentCallbackCase)
        },
        true
    )]
    public abstract class CallbacksAParsingResult
    {

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<PaymentCallback, T> paymentCallback,
            Func<FulfillmentCallback, T> fulfillmentCallback,
            Func<SignatureVerificationResult, T> signatureVerificationFailed,
            Func<T> unknown);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<PaymentCallback, T> paymentCallback = null,
            Func<FulfillmentCallback, T> fulfillmentCallback = null,
            Func<SignatureVerificationResult, T> signatureVerificationFailed = null,
            Func<T> unknown = null) =>
                Match(paymentCallback, fulfillmentCallback, signatureVerificationFailed, unknown);

        [JsonConverter(typeof(UnionTypeCaseConverter<PaymentCallbackCase, PaymentCallback>))]
        private sealed class PaymentCallbackCase : CallbacksAParsingResult, ICaseValue<PaymentCallbackCase, PaymentCallback>
        {
            public PaymentCallback Value;

            public override T Match<T>(
                Func<PaymentCallback, T> paymentCallback,
                Func<FulfillmentCallback, T> fulfillmentCallback,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   paymentCallback != null ? paymentCallback(Value) : default;

            public PaymentCallbackCase Set(PaymentCallback value)
            {
                Value = value;
                return this;
            }

            public PaymentCallback Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<FulfillmentCallbackCase, FulfillmentCallback>))]
        private sealed class FulfillmentCallbackCase : CallbacksAParsingResult, ICaseValue<FulfillmentCallbackCase, FulfillmentCallback>
        {
            public FulfillmentCallback Value;

            public override T Match<T>(
                Func<PaymentCallback, T> paymentCallback,
                Func<FulfillmentCallback, T> fulfillmentCallback,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   fulfillmentCallback != null ? fulfillmentCallback(Value) : default;

            public FulfillmentCallbackCase Set(FulfillmentCallback value)
            {
                Value = value;
                return this;
            }

            public FulfillmentCallback Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        /// <summary>
        /// Represents a parsing result when webhook signature verification fails.
        /// Contains details about the verification failure.
        /// </summary>
        internal sealed class SignatureVerificationFailed : CallbacksAParsingResult
        {
            public SignatureVerificationResult Value;

             public SignatureVerificationFailed(SignatureVerificationResult value)
             {
                 Value = value;
             }

            public override T Match<T>(
                Func<PaymentCallback, T> paymentCallback,
                Func<FulfillmentCallback, T> fulfillmentCallback,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   signatureVerificationFailed != null ? signatureVerificationFailed(Value) : default;
        }

        /// <summary>
        /// Represents an unknown or unrecognized webhook event parsing result.
        /// Used when the event type does not match any known cases.
        /// </summary>
        internal sealed class Unknown : CallbacksAParsingResult
        {
            public override T Match<T>(
                Func<PaymentCallback, T> paymentCallback,
                Func<FulfillmentCallback, T> fulfillmentCallback,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   unknown != null ? unknown() : default;
        }
    }
}