// <copyright file="CallbacksBParsingResult.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using WebhooksAndCallbacksAPI.Standard.Models;

namespace WebhooksAndCallbacksAPI.Standard.Events.Callbacks
{
    /// <summary>
    /// This is an event class for CallbacksBParsingResult.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<CallbacksBParsingResult>),
        new[] {
            typeof(EmailNotificationCallbackCase),
            typeof(SmsNotificationCallbackCase)
        },
        new[] {
            "email",
            "sms"
        },
        "notificationType",
        true
    )]
    public abstract class CallbacksBParsingResult
    {

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<NotificationCallback, T> emailNotificationCallback,
            Func<NotificationCallback, T> smsNotificationCallback,
            Func<SignatureVerificationResult, T> signatureVerificationFailed,
            Func<T> unknown);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<NotificationCallback, T> emailNotificationCallback = null,
            Func<NotificationCallback, T> smsNotificationCallback = null,
            Func<SignatureVerificationResult, T> signatureVerificationFailed = null,
            Func<T> unknown = null) =>
                Match(emailNotificationCallback, smsNotificationCallback, signatureVerificationFailed, unknown);

        [JsonConverter(typeof(UnionTypeCaseConverter<EmailNotificationCallbackCase, NotificationCallback>))]
        private sealed class EmailNotificationCallbackCase : CallbacksBParsingResult, ICaseValue<EmailNotificationCallbackCase, NotificationCallback>
        {
            public NotificationCallback Value;

            public override T Match<T>(
                Func<NotificationCallback, T> emailNotificationCallback,
                Func<NotificationCallback, T> smsNotificationCallback,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   emailNotificationCallback != null ? emailNotificationCallback(Value) : default;

            public EmailNotificationCallbackCase Set(NotificationCallback value)
            {
                Value = value;
                return this;
            }

            public NotificationCallback Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<SmsNotificationCallbackCase, NotificationCallback>))]
        private sealed class SmsNotificationCallbackCase : CallbacksBParsingResult, ICaseValue<SmsNotificationCallbackCase, NotificationCallback>
        {
            public NotificationCallback Value;

            public override T Match<T>(
                Func<NotificationCallback, T> emailNotificationCallback,
                Func<NotificationCallback, T> smsNotificationCallback,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   smsNotificationCallback != null ? smsNotificationCallback(Value) : default;

            public SmsNotificationCallbackCase Set(NotificationCallback value)
            {
                Value = value;
                return this;
            }

            public NotificationCallback Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        /// <summary>
        /// Represents a parsing result when webhook signature verification fails.
        /// Contains details about the verification failure.
        /// </summary>
        internal sealed class SignatureVerificationFailed : CallbacksBParsingResult
        {
            public SignatureVerificationResult Value;

             public SignatureVerificationFailed(SignatureVerificationResult value)
             {
                 Value = value;
             }

            public override T Match<T>(
                Func<NotificationCallback, T> emailNotificationCallback,
                Func<NotificationCallback, T> smsNotificationCallback,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   signatureVerificationFailed != null ? signatureVerificationFailed(Value) : default;
        }

        /// <summary>
        /// Represents an unknown or unrecognized webhook event parsing result.
        /// Used when the event type does not match any known cases.
        /// </summary>
        internal sealed class Unknown : CallbacksBParsingResult
        {
            public override T Match<T>(
                Func<NotificationCallback, T> emailNotificationCallback,
                Func<NotificationCallback, T> smsNotificationCallback,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   unknown != null ? unknown() : default;
        }
    }
}