// <copyright file="OAuthScopeOAuthACGEnum.cs" company="APIMatic">
// CypressTestAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace CypressTestAPI.Standard.Models
{
    /// <summary>
    /// OAuthScopeOAuthACGEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum OAuthScopeOAuthACGEnum
    {
        /// <summary>
        /// EnumFileRequestsread.
        /// </summary>
        [EnumMember(Value = "file_requests.read")]
        EnumFileRequestsread,

        /// <summary>
        /// Zahra.
        /// </summary>
        [EnumMember(Value = "zahra")]
        Zahra,

        /// <summary>
        /// Test1.
        /// </summary>
        [EnumMember(Value = "test1")]
        Test1,

        /// <summary>
        /// Selection.
        /// </summary>
        [EnumMember(Value = "selection")]
        Selection
    }
}