// <copyright file="Status11Enum.cs" company="APIMatic">
// CypressTestAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace CypressTestAPI.Standard.Models
{
    /// <summary>
    /// Status11Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status11Enum
    {
        /// <summary>
        /// Enumvalue1.
        /// </summary>
        [EnumMember(Value = "enumvalue1")]
        Enumvalue1,

        /// <summary>
        /// Enumvalue2.
        /// </summary>
        [EnumMember(Value = "enumvalue2")]
        Enumvalue2,

        /// <summary>
        /// Enumvalue3.
        /// </summary>
        [EnumMember(Value = "enumvalue3")]
        Enumvalue3
    }
}