// <copyright file="Status1Enum.cs" company="APIMatic">
// CypressTestAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using CypressTestAPI.Standard;
using CypressTestAPI.Standard.Utilities;
using Newtonsoft.Json;

namespace CypressTestAPI.Standard.Models
{
    /// <summary>
    /// Status1Enum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum Status1Enum
    {
        /// <summary>
        /// Enumvalue1.
        /// </summary>
        [EnumMember(Value = "enumvalue1")]
        Enumvalue1,

        /// <summary>
        /// Enumvalue2.
        /// </summary>
        [EnumMember(Value = "enumvalue2")]
        Enumvalue2,

        /// <summary>
        /// Enumvalue3.
        /// </summary>
        [EnumMember(Value = "enumvalue3")]
        Enumvalue3
    }
}