// <copyright file="ContentTypeEnum.cs" company="APIMatic">
// SwaggerPetstore.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace SwaggerPetstore.Standard.Models
{
    /// <summary>
    /// ContentTypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ContentTypeEnum
    {
        /// <summary>
        /// EnumApplicationxwwwformurlencoded.
        /// </summary>
        [EnumMember(Value = "application/x-www-form-urlencoded")]
        EnumApplicationxwwwformurlencoded
    }
}