// <copyright file="OAuthScopePetstoreAuthEnum.cs" company="APIMatic">
// SwaggerPetstore.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;

namespace SwaggerPetstore.Standard.Models
{
    /// <summary>
    /// OAuthScopePetstoreAuthEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum OAuthScopePetstoreAuthEnum
    {
        /// <summary>
        ///read your pets
        /// Readpets.
        /// </summary>
        [EnumMember(Value = "read:pets")]
        Readpets,

        /// <summary>
        ///modify pets in your account
        /// Writepets.
        /// </summary>
        [EnumMember(Value = "write:pets")]
        Writepets
    }

    internal static class OAuthScopePetstoreAuthEnumExtensions
    {
        internal static string GetValues(this IEnumerable<OAuthScopePetstoreAuthEnum> values) => values != null
            ? string.Join(" ", values.Select(s => s.GetValue()).Where(s => !string.IsNullOrEmpty(s)).ToArray())
            : null;

        private static string GetValue(this Enum value) =>
            value.GetType()
                .GetTypeInfo()
                .DeclaredMembers
                .SingleOrDefault(x => x.Name == value.ToString())
                ?.GetCustomAttribute<EnumMemberAttribute>(false)
                ?.Value;
    }
}