// <copyright file="WebhooksBParsingResult.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using WebhooksAndCallbacksAPI.Standard.Models.Containers;

namespace WebhooksAndCallbacksAPI.Standard.Events.Webhooks
{
    /// <summary>
    /// This is an event class for WebhooksBParsingResult.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<WebhooksBParsingResult>),
        new[] {
            typeof(Case0),
            typeof(Case1),
            typeof(Case2)
        },
        true
    )]
    public abstract class WebhooksBParsingResult
    {

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<UserNotificationEventBody, T> userNotificationEvent,
            Func<SystemNotificationEventBody, T> systemNotificationEvent,
            Func<InventoryChangeEventBody, T> inventoryChangeEvent,
            Func<SignatureVerificationResult, T> signatureVerificationFailed,
            Func<T> unknown);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<UserNotificationEventBody, T> userNotificationEvent = null,
            Func<SystemNotificationEventBody, T> systemNotificationEvent = null,
            Func<InventoryChangeEventBody, T> inventoryChangeEvent = null,
            Func<SignatureVerificationResult, T> signatureVerificationFailed = null,
            Func<T> unknown = null) =>
                Match(userNotificationEvent, systemNotificationEvent, inventoryChangeEvent, signatureVerificationFailed, unknown);

        [JsonConverter(typeof(UnionTypeCaseConverter<Case0, UserNotificationEventBody>))]
        private sealed class Case0 : WebhooksBParsingResult, ICaseValue<Case0, UserNotificationEventBody>
        {
            public UserNotificationEventBody Value;

            public override T Match<T>(
                Func<UserNotificationEventBody, T> userNotificationEvent,
                Func<SystemNotificationEventBody, T> systemNotificationEvent,
                Func<InventoryChangeEventBody, T> inventoryChangeEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   userNotificationEvent != null ? userNotificationEvent(Value) : default;

            public Case0 Set(UserNotificationEventBody value)
            {
                Value = value;
                return this;
            }

            public UserNotificationEventBody Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<Case1, SystemNotificationEventBody>))]
        private sealed class Case1 : WebhooksBParsingResult, ICaseValue<Case1, SystemNotificationEventBody>
        {
            public SystemNotificationEventBody Value;

            public override T Match<T>(
                Func<UserNotificationEventBody, T> userNotificationEvent,
                Func<SystemNotificationEventBody, T> systemNotificationEvent,
                Func<InventoryChangeEventBody, T> inventoryChangeEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   systemNotificationEvent != null ? systemNotificationEvent(Value) : default;

            public Case1 Set(SystemNotificationEventBody value)
            {
                Value = value;
                return this;
            }

            public SystemNotificationEventBody Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<Case2, InventoryChangeEventBody>))]
        private sealed class Case2 : WebhooksBParsingResult, ICaseValue<Case2, InventoryChangeEventBody>
        {
            public InventoryChangeEventBody Value;

            public override T Match<T>(
                Func<UserNotificationEventBody, T> userNotificationEvent,
                Func<SystemNotificationEventBody, T> systemNotificationEvent,
                Func<InventoryChangeEventBody, T> inventoryChangeEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   inventoryChangeEvent != null ? inventoryChangeEvent(Value) : default;

            public Case2 Set(InventoryChangeEventBody value)
            {
                Value = value;
                return this;
            }

            public InventoryChangeEventBody Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        /// <summary>
        /// Represents a parsing result when webhook signature verification fails.
        /// Contains details about the verification failure.
        /// </summary>
        internal sealed class SignatureVerificationFailed : WebhooksBParsingResult
        {
            public SignatureVerificationResult Value;

             public SignatureVerificationFailed(SignatureVerificationResult value)
             {
                 Value = value;
             }

            public override T Match<T>(
                Func<UserNotificationEventBody, T> userNotificationEvent,
                Func<SystemNotificationEventBody, T> systemNotificationEvent,
                Func<InventoryChangeEventBody, T> inventoryChangeEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   signatureVerificationFailed != null ? signatureVerificationFailed(Value) : default;
        }

        /// <summary>
        /// Represents an unknown or unrecognized webhook event parsing result.
        /// Used when the event type does not match any known cases.
        /// </summary>
        internal sealed class Unknown : WebhooksBParsingResult
        {
            public override T Match<T>(
                Func<UserNotificationEventBody, T> userNotificationEvent,
                Func<SystemNotificationEventBody, T> systemNotificationEvent,
                Func<InventoryChangeEventBody, T> inventoryChangeEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   unknown != null ? unknown() : default;
        }
    }
}