// <copyright file="WebhooksNoVerificationParsingResult.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using WebhooksAndCallbacksAPI.Standard.Models;
using WebhooksAndCallbacksAPI.Standard.Models.Containers;

namespace WebhooksAndCallbacksAPI.Standard.Events.Webhooks
{
    /// <summary>
    /// This is an event class for WebhooksNoVerificationParsingResult.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<WebhooksNoVerificationParsingResult>),
        new[] {
            typeof(AuditLogEventCase),
            typeof(Case1)
        },
        true
    )]
    public abstract class WebhooksNoVerificationParsingResult
    {

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<AuditLogEvent, T> auditLogEvent,
            Func<RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, T> rootLevelPrimitiveOneOfEvent,
            Func<T> unknown);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<AuditLogEvent, T> auditLogEvent = null,
            Func<RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, T> rootLevelPrimitiveOneOfEvent = null,
            Func<T> unknown = null) =>
                Match(auditLogEvent, rootLevelPrimitiveOneOfEvent, unknown);

        [JsonConverter(typeof(UnionTypeCaseConverter<AuditLogEventCase, AuditLogEvent>))]
        private sealed class AuditLogEventCase : WebhooksNoVerificationParsingResult, ICaseValue<AuditLogEventCase, AuditLogEvent>
        {
            public AuditLogEvent Value;

            public override T Match<T>(
                Func<AuditLogEvent, T> auditLogEvent,
                Func<RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, T> rootLevelPrimitiveOneOfEvent,
                Func<T> unknown) =>
                   auditLogEvent != null ? auditLogEvent(Value) : default;

            public AuditLogEventCase Set(AuditLogEvent value)
            {
                Value = value;
                return this;
            }

            public AuditLogEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<Case1, RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody>))]
        private sealed class Case1 : WebhooksNoVerificationParsingResult, ICaseValue<Case1, RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody>
        {
            public RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody Value;

            public override T Match<T>(
                Func<AuditLogEvent, T> auditLogEvent,
                Func<RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, T> rootLevelPrimitiveOneOfEvent,
                Func<T> unknown) =>
                   rootLevelPrimitiveOneOfEvent != null ? rootLevelPrimitiveOneOfEvent(Value) : default;

            public Case1 Set(RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody value)
            {
                Value = value;
                return this;
            }

            public RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        /// <summary>
        /// Represents an unknown or unrecognized webhook event parsing result.
        /// Used when the event type does not match any known cases.
        /// </summary>
        internal sealed class Unknown : WebhooksNoVerificationParsingResult
        {
            public override T Match<T>(
                Func<AuditLogEvent, T> auditLogEvent,
                Func<RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, T> rootLevelPrimitiveOneOfEvent,
                Func<T> unknown) =>
                   unknown != null ? unknown() : default;
        }
    }
}