// <copyright file="WebhooksNoVerificationHandler.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using System.Threading;
using System.Threading.Tasks;
using WebhooksAndCallbacksAPI.Standard.Http.Request;

namespace WebhooksAndCallbacksAPI.Standard.Events.Webhooks
{
    /// <summary>
    /// WebhooksNoVerificationHandler to handle event parsing.
    /// </summary>
    public static class WebhooksNoVerificationHandler
    {
        /// <summary>
        /// Parses the incoming HTTP request data and deserializes it into an <see cref="WebhooksNoVerificationParsingResult"/> object.
        /// Returns <see cref="WebhooksNoVerificationParsingResult.Unknown"/> if the payload is empty or deserialization fails.
        /// </summary>
        /// <param name="request">The HTTP request data containing the event payload.</param>
        /// <param name="cancellationToken">Token to cancel the operation.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result contains the parsed <see cref="WebhooksNoVerificationParsingResult"/> object,
        /// or <see cref="WebhooksNoVerificationParsingResult.Unknown"/> if parsing fails.
        /// </returns>
        public static async Task<WebhooksNoVerificationParsingResult> ParseEventAsync(HttpRequestData request, CancellationToken cancellationToken = default)
        {
            var payload = await request.ReadBodyAsStringAsync(cancellationToken).ConfigureAwait(false);
    
            if (string.IsNullOrEmpty(payload))
                return new WebhooksNoVerificationParsingResult.Unknown();
    
            var settings = new JsonSerializerSettings
            {
                MissingMemberHandling = MissingMemberHandling.Error
            };
    
            var accountsEvent = JsonConvert.DeserializeObject<WebhooksNoVerificationParsingResult>(payload, settings);
            return accountsEvent ?? new WebhooksNoVerificationParsingResult.Unknown();
        }
    }
}