// <copyright file="WebhooksParsingResult.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using WebhooksAndCallbacksAPI.Standard.Models;

namespace WebhooksAndCallbacksAPI.Standard.Events.Webhooks
{
    /// <summary>
    /// This is an event class for WebhooksParsingResult.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<WebhooksParsingResult>),
        new[] {
            typeof(OrderCreatedNewTestingMyNewyTesinggggggTocHejcjkCase),
            typeof(OrderUpdatedCase),
            typeof(PaymentCompletedCase),
            typeof(PrimitiveCollectionEventCase)
        },
        true
    )]
    public abstract class WebhooksParsingResult
    {

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<OrderCreatedEvent, T> orderCreatedNewTestingMyNewyTesinggggggTocHejcjk,
            Func<OrderUpdatedEvent, T> orderUpdated,
            Func<PaymentCompletedEvent, T> paymentCompleted,
            Func<PrimitiveCollectionEvent, T> primitiveCollectionEvent,
            Func<SignatureVerificationResult, T> signatureVerificationFailed,
            Func<T> unknown);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<OrderCreatedEvent, T> orderCreatedNewTestingMyNewyTesinggggggTocHejcjk = null,
            Func<OrderUpdatedEvent, T> orderUpdated = null,
            Func<PaymentCompletedEvent, T> paymentCompleted = null,
            Func<PrimitiveCollectionEvent, T> primitiveCollectionEvent = null,
            Func<SignatureVerificationResult, T> signatureVerificationFailed = null,
            Func<T> unknown = null) =>
                Match(orderCreatedNewTestingMyNewyTesinggggggTocHejcjk, orderUpdated, paymentCompleted, primitiveCollectionEvent, signatureVerificationFailed, unknown);

        [JsonConverter(typeof(UnionTypeCaseConverter<OrderCreatedNewTestingMyNewyTesinggggggTocHejcjkCase, OrderCreatedEvent>))]
        private sealed class OrderCreatedNewTestingMyNewyTesinggggggTocHejcjkCase : WebhooksParsingResult, ICaseValue<OrderCreatedNewTestingMyNewyTesinggggggTocHejcjkCase, OrderCreatedEvent>
        {
            public OrderCreatedEvent Value;

            public override T Match<T>(
                Func<OrderCreatedEvent, T> orderCreatedNewTestingMyNewyTesinggggggTocHejcjk,
                Func<OrderUpdatedEvent, T> orderUpdated,
                Func<PaymentCompletedEvent, T> paymentCompleted,
                Func<PrimitiveCollectionEvent, T> primitiveCollectionEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   orderCreatedNewTestingMyNewyTesinggggggTocHejcjk != null ? orderCreatedNewTestingMyNewyTesinggggggTocHejcjk(Value) : default;

            public OrderCreatedNewTestingMyNewyTesinggggggTocHejcjkCase Set(OrderCreatedEvent value)
            {
                Value = value;
                return this;
            }

            public OrderCreatedEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<OrderUpdatedCase, OrderUpdatedEvent>))]
        private sealed class OrderUpdatedCase : WebhooksParsingResult, ICaseValue<OrderUpdatedCase, OrderUpdatedEvent>
        {
            public OrderUpdatedEvent Value;

            public override T Match<T>(
                Func<OrderCreatedEvent, T> orderCreatedNewTestingMyNewyTesinggggggTocHejcjk,
                Func<OrderUpdatedEvent, T> orderUpdated,
                Func<PaymentCompletedEvent, T> paymentCompleted,
                Func<PrimitiveCollectionEvent, T> primitiveCollectionEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   orderUpdated != null ? orderUpdated(Value) : default;

            public OrderUpdatedCase Set(OrderUpdatedEvent value)
            {
                Value = value;
                return this;
            }

            public OrderUpdatedEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<PaymentCompletedCase, PaymentCompletedEvent>))]
        private sealed class PaymentCompletedCase : WebhooksParsingResult, ICaseValue<PaymentCompletedCase, PaymentCompletedEvent>
        {
            public PaymentCompletedEvent Value;

            public override T Match<T>(
                Func<OrderCreatedEvent, T> orderCreatedNewTestingMyNewyTesinggggggTocHejcjk,
                Func<OrderUpdatedEvent, T> orderUpdated,
                Func<PaymentCompletedEvent, T> paymentCompleted,
                Func<PrimitiveCollectionEvent, T> primitiveCollectionEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   paymentCompleted != null ? paymentCompleted(Value) : default;

            public PaymentCompletedCase Set(PaymentCompletedEvent value)
            {
                Value = value;
                return this;
            }

            public PaymentCompletedEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<PrimitiveCollectionEventCase, PrimitiveCollectionEvent>))]
        private sealed class PrimitiveCollectionEventCase : WebhooksParsingResult, ICaseValue<PrimitiveCollectionEventCase, PrimitiveCollectionEvent>
        {
            public PrimitiveCollectionEvent Value;

            public override T Match<T>(
                Func<OrderCreatedEvent, T> orderCreatedNewTestingMyNewyTesinggggggTocHejcjk,
                Func<OrderUpdatedEvent, T> orderUpdated,
                Func<PaymentCompletedEvent, T> paymentCompleted,
                Func<PrimitiveCollectionEvent, T> primitiveCollectionEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   primitiveCollectionEvent != null ? primitiveCollectionEvent(Value) : default;

            public PrimitiveCollectionEventCase Set(PrimitiveCollectionEvent value)
            {
                Value = value;
                return this;
            }

            public PrimitiveCollectionEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        /// <summary>
        /// Represents a parsing result when webhook signature verification fails.
        /// Contains details about the verification failure.
        /// </summary>
        internal sealed class SignatureVerificationFailed : WebhooksParsingResult
        {
            public SignatureVerificationResult Value;

             public SignatureVerificationFailed(SignatureVerificationResult value)
             {
                 Value = value;
             }

            public override T Match<T>(
                Func<OrderCreatedEvent, T> orderCreatedNewTestingMyNewyTesinggggggTocHejcjk,
                Func<OrderUpdatedEvent, T> orderUpdated,
                Func<PaymentCompletedEvent, T> paymentCompleted,
                Func<PrimitiveCollectionEvent, T> primitiveCollectionEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   signatureVerificationFailed != null ? signatureVerificationFailed(Value) : default;
        }

        /// <summary>
        /// Represents an unknown or unrecognized webhook event parsing result.
        /// Used when the event type does not match any known cases.
        /// </summary>
        internal sealed class Unknown : WebhooksParsingResult
        {
            public override T Match<T>(
                Func<OrderCreatedEvent, T> orderCreatedNewTestingMyNewyTesinggggggTocHejcjk,
                Func<OrderUpdatedEvent, T> orderUpdated,
                Func<PaymentCompletedEvent, T> paymentCompleted,
                Func<PrimitiveCollectionEvent, T> primitiveCollectionEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   unknown != null ? unknown() : default;
        }
    }
}