// <copyright file="WebhooksCParsingResult.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;

namespace WebhooksAndCallbacksAPI.Standard.Events.Webhooks
{
    /// <summary>
    /// This is an event class for WebhooksCParsingResult.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<WebhooksCParsingResult>),
        new[] {
            typeof(StringEventCase),
            typeof(IntEventCase),
            typeof(NumberListEventCase),
            typeof(StringMapEventCase)
        },
        true
    )]
    public abstract class WebhooksCParsingResult
    {

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<string, T> stringEvent,
            Func<int, T> intEvent,
            Func<List<double>, T> numberListEvent,
            Func<Dictionary<string, string>, T> stringMapEvent,
            Func<SignatureVerificationResult, T> signatureVerificationFailed,
            Func<T> unknown);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<string, T> stringEvent = null,
            Func<int, T> intEvent = null,
            Func<List<double>, T> numberListEvent = null,
            Func<Dictionary<string, string>, T> stringMapEvent = null,
            Func<SignatureVerificationResult, T> signatureVerificationFailed = null,
            Func<T> unknown = null) =>
                Match(stringEvent, intEvent, numberListEvent, stringMapEvent, signatureVerificationFailed, unknown);

        [JsonConverter(typeof(UnionTypeCaseConverter<StringEventCase, string>), JTokenType.String, JTokenType.Null)]
        private sealed class StringEventCase : WebhooksCParsingResult, ICaseValue<StringEventCase, string>
        {
            public string Value;

            public override T Match<T>(
                Func<string, T> stringEvent,
                Func<int, T> intEvent,
                Func<List<double>, T> numberListEvent,
                Func<Dictionary<string, string>, T> stringMapEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   stringEvent != null ? stringEvent(Value) : default;

            public StringEventCase Set(string value)
            {
                Value = value;
                return this;
            }

            public string Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<IntEventCase, int>), JTokenType.Integer)]
        private sealed class IntEventCase : WebhooksCParsingResult, ICaseValue<IntEventCase, int>
        {
            public int Value;

            public override T Match<T>(
                Func<string, T> stringEvent,
                Func<int, T> intEvent,
                Func<List<double>, T> numberListEvent,
                Func<Dictionary<string, string>, T> stringMapEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   intEvent != null ? intEvent(Value) : default;

            public IntEventCase Set(int value)
            {
                Value = value;
                return this;
            }

            public int Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<NumberListEventCase, List<double>>), JTokenType.Float)]
        private sealed class NumberListEventCase : WebhooksCParsingResult, ICaseValue<NumberListEventCase, List<double>>
        {
            public List<double> Value;

            public override T Match<T>(
                Func<string, T> stringEvent,
                Func<int, T> intEvent,
                Func<List<double>, T> numberListEvent,
                Func<Dictionary<string, string>, T> stringMapEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   numberListEvent != null ? numberListEvent(Value) : default;

            public NumberListEventCase Set(List<double> value)
            {
                Value = value;
                return this;
            }

            public List<double> Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<StringMapEventCase, Dictionary<string, string>>), JTokenType.String, JTokenType.Null)]
        private sealed class StringMapEventCase : WebhooksCParsingResult, ICaseValue<StringMapEventCase, Dictionary<string, string>>
        {
            public Dictionary<string, string> Value;

            public override T Match<T>(
                Func<string, T> stringEvent,
                Func<int, T> intEvent,
                Func<List<double>, T> numberListEvent,
                Func<Dictionary<string, string>, T> stringMapEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   stringMapEvent != null ? stringMapEvent(Value) : default;

            public StringMapEventCase Set(Dictionary<string, string> value)
            {
                Value = value;
                return this;
            }

            public Dictionary<string, string> Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        /// <summary>
        /// Represents a parsing result when webhook signature verification fails.
        /// Contains details about the verification failure.
        /// </summary>
        internal sealed class SignatureVerificationFailed : WebhooksCParsingResult
        {
            public SignatureVerificationResult Value;

             public SignatureVerificationFailed(SignatureVerificationResult value)
             {
                 Value = value;
             }

            public override T Match<T>(
                Func<string, T> stringEvent,
                Func<int, T> intEvent,
                Func<List<double>, T> numberListEvent,
                Func<Dictionary<string, string>, T> stringMapEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   signatureVerificationFailed != null ? signatureVerificationFailed(Value) : default;
        }

        /// <summary>
        /// Represents an unknown or unrecognized webhook event parsing result.
        /// Used when the event type does not match any known cases.
        /// </summary>
        internal sealed class Unknown : WebhooksCParsingResult
        {
            public override T Match<T>(
                Func<string, T> stringEvent,
                Func<int, T> intEvent,
                Func<List<double>, T> numberListEvent,
                Func<Dictionary<string, string>, T> stringMapEvent,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   unknown != null ? unknown() : default;
        }
    }
}