// <copyright file="WebhooksAParsingResult.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using WebhooksAndCallbacksAPI.Standard.Models;

namespace WebhooksAndCallbacksAPI.Standard.Events.Webhooks
{
    /// <summary>
    /// This is an event class for WebhooksAParsingResult.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<WebhooksAParsingResult>),
        new[] {
            typeof(PaymentStatusUpdatedCase),
            typeof(PaymentStatusCreatedCase)
        },
        true
    )]
    public abstract class WebhooksAParsingResult
    {

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<PaymentStatusUpdatedEvent, T> paymentStatusUpdated,
            Func<PaymentStatusCreatedEvent, T> paymentStatusCreated,
            Func<SignatureVerificationResult, T> signatureVerificationFailed,
            Func<T> unknown);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<PaymentStatusUpdatedEvent, T> paymentStatusUpdated = null,
            Func<PaymentStatusCreatedEvent, T> paymentStatusCreated = null,
            Func<SignatureVerificationResult, T> signatureVerificationFailed = null,
            Func<T> unknown = null) =>
                Match(paymentStatusUpdated, paymentStatusCreated, signatureVerificationFailed, unknown);

        [JsonConverter(typeof(UnionTypeCaseConverter<PaymentStatusUpdatedCase, PaymentStatusUpdatedEvent>))]
        private sealed class PaymentStatusUpdatedCase : WebhooksAParsingResult, ICaseValue<PaymentStatusUpdatedCase, PaymentStatusUpdatedEvent>
        {
            public PaymentStatusUpdatedEvent Value;

            public override T Match<T>(
                Func<PaymentStatusUpdatedEvent, T> paymentStatusUpdated,
                Func<PaymentStatusCreatedEvent, T> paymentStatusCreated,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   paymentStatusUpdated != null ? paymentStatusUpdated(Value) : default;

            public PaymentStatusUpdatedCase Set(PaymentStatusUpdatedEvent value)
            {
                Value = value;
                return this;
            }

            public PaymentStatusUpdatedEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<PaymentStatusCreatedCase, PaymentStatusCreatedEvent>))]
        private sealed class PaymentStatusCreatedCase : WebhooksAParsingResult, ICaseValue<PaymentStatusCreatedCase, PaymentStatusCreatedEvent>
        {
            public PaymentStatusCreatedEvent Value;

            public override T Match<T>(
                Func<PaymentStatusUpdatedEvent, T> paymentStatusUpdated,
                Func<PaymentStatusCreatedEvent, T> paymentStatusCreated,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   paymentStatusCreated != null ? paymentStatusCreated(Value) : default;

            public PaymentStatusCreatedCase Set(PaymentStatusCreatedEvent value)
            {
                Value = value;
                return this;
            }

            public PaymentStatusCreatedEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        /// <summary>
        /// Represents a parsing result when webhook signature verification fails.
        /// Contains details about the verification failure.
        /// </summary>
        internal sealed class SignatureVerificationFailed : WebhooksAParsingResult
        {
            public SignatureVerificationResult Value;

             public SignatureVerificationFailed(SignatureVerificationResult value)
             {
                 Value = value;
             }

            public override T Match<T>(
                Func<PaymentStatusUpdatedEvent, T> paymentStatusUpdated,
                Func<PaymentStatusCreatedEvent, T> paymentStatusCreated,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   signatureVerificationFailed != null ? signatureVerificationFailed(Value) : default;
        }

        /// <summary>
        /// Represents an unknown or unrecognized webhook event parsing result.
        /// Used when the event type does not match any known cases.
        /// </summary>
        internal sealed class Unknown : WebhooksAParsingResult
        {
            public override T Match<T>(
                Func<PaymentStatusUpdatedEvent, T> paymentStatusUpdated,
                Func<PaymentStatusCreatedEvent, T> paymentStatusCreated,
                Func<SignatureVerificationResult, T> signatureVerificationFailed,
                Func<T> unknown) =>
                   unknown != null ? unknown() : default;
        }
    }
}