// <copyright file="InventoryChangeEventBody.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace WebhooksAndCallbacksAPI.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<InventoryChangeEventBody>),
        new[] {
            typeof(InventoryStockIncreaseEventCase),
            typeof(InventoryStockDecreaseEventCase),
            typeof(InventoryStockDepletedEventCase)
        },
        true
    )]
    public abstract class InventoryChangeEventBody
    {
        /// <summary>
        /// This is InventoryStockIncreaseEvent case.
        /// </summary>
        /// <returns>
        /// The InventoryChangeEventBody instance, wrapping the provided InventoryStockIncreaseEvent value.
        /// </returns>
        public static InventoryChangeEventBody FromInventoryStockIncreaseEvent(InventoryStockIncreaseEvent inventoryStockIncreaseEvent)
        {
            return new InventoryStockIncreaseEventCase().Set(inventoryStockIncreaseEvent);
        }

        /// <summary>
        /// This is InventoryStockDecreaseEvent case.
        /// </summary>
        /// <returns>
        /// The InventoryChangeEventBody instance, wrapping the provided InventoryStockDecreaseEvent value.
        /// </returns>
        public static InventoryChangeEventBody FromInventoryStockDecreaseEvent(InventoryStockDecreaseEvent inventoryStockDecreaseEvent)
        {
            return new InventoryStockDecreaseEventCase().Set(inventoryStockDecreaseEvent);
        }

        /// <summary>
        /// This is InventoryStockDepletedEvent case.
        /// </summary>
        /// <returns>
        /// The InventoryChangeEventBody instance, wrapping the provided InventoryStockDepletedEvent value.
        /// </returns>
        public static InventoryChangeEventBody FromInventoryStockDepletedEvent(InventoryStockDepletedEvent inventoryStockDepletedEvent)
        {
            return new InventoryStockDepletedEventCase().Set(inventoryStockDepletedEvent);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<InventoryStockIncreaseEvent, T> inventoryStockIncreaseEvent,
            Func<InventoryStockDecreaseEvent, T> inventoryStockDecreaseEvent,
            Func<InventoryStockDepletedEvent, T> inventoryStockDepletedEvent);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<InventoryStockIncreaseEvent, T> inventoryStockIncreaseEvent = null,
            Func<InventoryStockDecreaseEvent, T> inventoryStockDecreaseEvent = null,
            Func<InventoryStockDepletedEvent, T> inventoryStockDepletedEvent = null) =>
                Match(inventoryStockIncreaseEvent, inventoryStockDecreaseEvent, inventoryStockDepletedEvent);

        [JsonConverter(typeof(UnionTypeCaseConverter<InventoryStockIncreaseEventCase, InventoryStockIncreaseEvent>))]
        private sealed class InventoryStockIncreaseEventCase : InventoryChangeEventBody, ICaseValue<InventoryStockIncreaseEventCase, InventoryStockIncreaseEvent>
        {
            public InventoryStockIncreaseEvent Value;

            public override T Match<T>(
                Func<InventoryStockIncreaseEvent, T> inventoryStockIncreaseEvent,
                Func<InventoryStockDecreaseEvent, T> inventoryStockDecreaseEvent,
                Func<InventoryStockDepletedEvent, T> inventoryStockDepletedEvent) =>
                   inventoryStockIncreaseEvent != null ? inventoryStockIncreaseEvent(Value) : default;

            public InventoryStockIncreaseEventCase Set(InventoryStockIncreaseEvent value)
            {
                Value = value;
                return this;
            }

            public InventoryStockIncreaseEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<InventoryStockDecreaseEventCase, InventoryStockDecreaseEvent>))]
        private sealed class InventoryStockDecreaseEventCase : InventoryChangeEventBody, ICaseValue<InventoryStockDecreaseEventCase, InventoryStockDecreaseEvent>
        {
            public InventoryStockDecreaseEvent Value;

            public override T Match<T>(
                Func<InventoryStockIncreaseEvent, T> inventoryStockIncreaseEvent,
                Func<InventoryStockDecreaseEvent, T> inventoryStockDecreaseEvent,
                Func<InventoryStockDepletedEvent, T> inventoryStockDepletedEvent) =>
                   inventoryStockDecreaseEvent != null ? inventoryStockDecreaseEvent(Value) : default;

            public InventoryStockDecreaseEventCase Set(InventoryStockDecreaseEvent value)
            {
                Value = value;
                return this;
            }

            public InventoryStockDecreaseEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<InventoryStockDepletedEventCase, InventoryStockDepletedEvent>))]
        private sealed class InventoryStockDepletedEventCase : InventoryChangeEventBody, ICaseValue<InventoryStockDepletedEventCase, InventoryStockDepletedEvent>
        {
            public InventoryStockDepletedEvent Value;

            public override T Match<T>(
                Func<InventoryStockIncreaseEvent, T> inventoryStockIncreaseEvent,
                Func<InventoryStockDecreaseEvent, T> inventoryStockDecreaseEvent,
                Func<InventoryStockDepletedEvent, T> inventoryStockDepletedEvent) =>
                   inventoryStockDepletedEvent != null ? inventoryStockDepletedEvent(Value) : default;

            public InventoryStockDepletedEventCase Set(InventoryStockDepletedEvent value)
            {
                Value = value;
                return this;
            }

            public InventoryStockDepletedEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}