// <copyright file="OrderCreatedEventDeliveryDetails.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;

namespace WebhooksAndCallbacksAPI.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<OrderCreatedEventDeliveryDetails>),
        new[] {
            typeof(MStringCase),
            typeof(DeliveryDetailsCase)
        },
        true
    )]
    public abstract class OrderCreatedEventDeliveryDetails
    {
        /// <summary>
        /// This is String case.
        /// </summary>
        /// <returns>
        /// The OrderCreatedEventDeliveryDetails instance, wrapping the provided string value.
        /// </returns>
        public static OrderCreatedEventDeliveryDetails FromString(string mString)
        {
            return new MStringCase().Set(mString);
        }

        /// <summary>
        /// This is DeliveryDetails case.
        /// </summary>
        /// <returns>
        /// The OrderCreatedEventDeliveryDetails instance, wrapping the provided DeliveryDetails value.
        /// </returns>
        public static OrderCreatedEventDeliveryDetails FromDeliveryDetails(DeliveryDetails deliveryDetails)
        {
            return new DeliveryDetailsCase().Set(deliveryDetails);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(Func<string, T> mString, Func<DeliveryDetails, T> deliveryDetails);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(Func<string, T> mString = null, Func<DeliveryDetails, T> deliveryDetails = null) =>
                Match(mString, deliveryDetails);

        [JsonConverter(typeof(UnionTypeCaseConverter<MStringCase, string>), JTokenType.String, JTokenType.Null)]
        private sealed class MStringCase : OrderCreatedEventDeliveryDetails, ICaseValue<MStringCase, string>
        {
            public string Value;

            public override T Match<T>(Func<string, T> mString, Func<DeliveryDetails, T> deliveryDetails) =>
                   mString != null ? mString(Value) : default;

            public MStringCase Set(string value)
            {
                Value = value;
                return this;
            }

            public string Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<DeliveryDetailsCase, DeliveryDetails>))]
        private sealed class DeliveryDetailsCase : OrderCreatedEventDeliveryDetails, ICaseValue<DeliveryDetailsCase, DeliveryDetails>
        {
            public DeliveryDetails Value;

            public override T Match<T>(Func<string, T> mString, Func<DeliveryDetails, T> deliveryDetails) =>
                   deliveryDetails != null ? deliveryDetails(Value) : default;

            public DeliveryDetailsCase Set(DeliveryDetails value)
            {
                Value = value;
                return this;
            }

            public DeliveryDetails Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}