// <copyright file="RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;

namespace WebhooksAndCallbacksAPI.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody>),
        new[] {
            typeof(RootLevelPrimitiveOneOfEventRequestCase),
            typeof(NumberCase),
            typeof(ListOfRootLevelPrimitiveOneOfEventRequest1Case),
            typeof(ListOfNumberCase)
        },
        true
    )]
    public abstract class RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody
    {
        /// <summary>
        /// This is RootLevelPrimitiveOneOfEvent Request case.
        /// </summary>
        /// <returns>
        /// The RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody instance, wrapping the provided RootLevelPrimitiveOneOfEventRequest value.
        /// </returns>
        public static RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody FromRootLevelPrimitiveOneOfEventRequest(RootLevelPrimitiveOneOfEventRequest rootLevelPrimitiveOneOfEventRequest)
        {
            return new RootLevelPrimitiveOneOfEventRequestCase().Set(rootLevelPrimitiveOneOfEventRequest);
        }

        /// <summary>
        /// This is Number case.
        /// </summary>
        /// <returns>
        /// The RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody instance, wrapping the provided int value.
        /// </returns>
        public static RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody FromNumber(int number)
        {
            return new NumberCase().Set(number);
        }

        /// <summary>
        /// This is List of RootLevelPrimitiveOneOfEvent Request1 case.
        /// </summary>
        /// <returns>
        /// The RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody instance, wrapping the provided List&lt;RootLevelPrimitiveOneOfEventRequest1&gt; value.
        /// </returns>
        public static RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody FromListOfRootLevelPrimitiveOneOfEventRequest1(List<RootLevelPrimitiveOneOfEventRequest1> listOfRootLevelPrimitiveOneOfEventRequest1)
        {
            return new ListOfRootLevelPrimitiveOneOfEventRequest1Case().Set(listOfRootLevelPrimitiveOneOfEventRequest1);
        }

        /// <summary>
        /// This is List of Number case.
        /// </summary>
        /// <returns>
        /// The RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody instance, wrapping the provided List&lt;int&gt; value.
        /// </returns>
        public static RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody FromListOfNumber(List<int> listOfNumber)
        {
            return new ListOfNumberCase().Set(listOfNumber);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<RootLevelPrimitiveOneOfEventRequest, T> rootLevelPrimitiveOneOfEventRequest,
            Func<int, T> number,
            Func<List<RootLevelPrimitiveOneOfEventRequest1>, T> listOfRootLevelPrimitiveOneOfEventRequest1,
            Func<List<int>, T> listOfNumber);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<RootLevelPrimitiveOneOfEventRequest, T> rootLevelPrimitiveOneOfEventRequest = null,
            Func<int, T> number = null,
            Func<List<RootLevelPrimitiveOneOfEventRequest1>, T> listOfRootLevelPrimitiveOneOfEventRequest1 = null,
            Func<List<int>, T> listOfNumber = null) =>
                Match(rootLevelPrimitiveOneOfEventRequest, number, listOfRootLevelPrimitiveOneOfEventRequest1, listOfNumber);

        [JsonConverter(typeof(UnionTypeCaseConverter<RootLevelPrimitiveOneOfEventRequestCase, RootLevelPrimitiveOneOfEventRequest>))]
        private sealed class RootLevelPrimitiveOneOfEventRequestCase : RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, ICaseValue<RootLevelPrimitiveOneOfEventRequestCase, RootLevelPrimitiveOneOfEventRequest>
        {
            public RootLevelPrimitiveOneOfEventRequest Value;

            public override T Match<T>(
                Func<RootLevelPrimitiveOneOfEventRequest, T> rootLevelPrimitiveOneOfEventRequest,
                Func<int, T> number,
                Func<List<RootLevelPrimitiveOneOfEventRequest1>, T> listOfRootLevelPrimitiveOneOfEventRequest1,
                Func<List<int>, T> listOfNumber) =>
                   rootLevelPrimitiveOneOfEventRequest != null ? rootLevelPrimitiveOneOfEventRequest(Value) : default;

            public RootLevelPrimitiveOneOfEventRequestCase Set(RootLevelPrimitiveOneOfEventRequest value)
            {
                Value = value;
                return this;
            }

            public RootLevelPrimitiveOneOfEventRequest Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<NumberCase, int>), JTokenType.Integer)]
        private sealed class NumberCase : RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, ICaseValue<NumberCase, int>
        {
            public int Value;

            public override T Match<T>(
                Func<RootLevelPrimitiveOneOfEventRequest, T> rootLevelPrimitiveOneOfEventRequest,
                Func<int, T> number,
                Func<List<RootLevelPrimitiveOneOfEventRequest1>, T> listOfRootLevelPrimitiveOneOfEventRequest1,
                Func<List<int>, T> listOfNumber) =>
                   number != null ? number(Value) : default;

            public NumberCase Set(int value)
            {
                Value = value;
                return this;
            }

            public int Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ListOfRootLevelPrimitiveOneOfEventRequest1Case, List<RootLevelPrimitiveOneOfEventRequest1>>))]
        private sealed class ListOfRootLevelPrimitiveOneOfEventRequest1Case : RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, ICaseValue<ListOfRootLevelPrimitiveOneOfEventRequest1Case, List<RootLevelPrimitiveOneOfEventRequest1>>
        {
            public List<RootLevelPrimitiveOneOfEventRequest1> Value;

            public override T Match<T>(
                Func<RootLevelPrimitiveOneOfEventRequest, T> rootLevelPrimitiveOneOfEventRequest,
                Func<int, T> number,
                Func<List<RootLevelPrimitiveOneOfEventRequest1>, T> listOfRootLevelPrimitiveOneOfEventRequest1,
                Func<List<int>, T> listOfNumber) =>
                   listOfRootLevelPrimitiveOneOfEventRequest1 != null ? listOfRootLevelPrimitiveOneOfEventRequest1(Value) : default;

            public ListOfRootLevelPrimitiveOneOfEventRequest1Case Set(List<RootLevelPrimitiveOneOfEventRequest1> value)
            {
                Value = value;
                return this;
            }

            public List<RootLevelPrimitiveOneOfEventRequest1> Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<ListOfNumberCase, List<int>>), JTokenType.Integer)]
        private sealed class ListOfNumberCase : RootLevelOneOfPrimitiveEventRootLevelPrimitiveOneOfBody, ICaseValue<ListOfNumberCase, List<int>>
        {
            public List<int> Value;

            public override T Match<T>(
                Func<RootLevelPrimitiveOneOfEventRequest, T> rootLevelPrimitiveOneOfEventRequest,
                Func<int, T> number,
                Func<List<RootLevelPrimitiveOneOfEventRequest1>, T> listOfRootLevelPrimitiveOneOfEventRequest1,
                Func<List<int>, T> listOfNumber) =>
                   listOfNumber != null ? listOfNumber(Value) : default;

            public ListOfNumberCase Set(List<int> value)
            {
                Value = value;
                return this;
            }

            public List<int> Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}