// <copyright file="SystemNotificationEventBody.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace WebhooksAndCallbacksAPI.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<SystemNotificationEventBody>),
        new[] {
            typeof(SystemAlertNotificationEventCase),
            typeof(SystemMaintenanceNotificationEventCase),
            typeof(SystemPerformanceNotificationEventCase)
        },
        true
    )]
    public abstract class SystemNotificationEventBody
    {
        /// <summary>
        /// This is SystemAlertNotificationEvent case.
        /// </summary>
        /// <returns>
        /// The SystemNotificationEventBody instance, wrapping the provided SystemAlertNotificationEvent value.
        /// </returns>
        public static SystemNotificationEventBody FromSystemAlertNotificationEvent(SystemAlertNotificationEvent systemAlertNotificationEvent)
        {
            return new SystemAlertNotificationEventCase().Set(systemAlertNotificationEvent);
        }

        /// <summary>
        /// This is SystemMaintenanceNotificationEvent case.
        /// </summary>
        /// <returns>
        /// The SystemNotificationEventBody instance, wrapping the provided SystemMaintenanceNotificationEvent value.
        /// </returns>
        public static SystemNotificationEventBody FromSystemMaintenanceNotificationEvent(SystemMaintenanceNotificationEvent systemMaintenanceNotificationEvent)
        {
            return new SystemMaintenanceNotificationEventCase().Set(systemMaintenanceNotificationEvent);
        }

        /// <summary>
        /// This is SystemPerformanceNotificationEvent case.
        /// </summary>
        /// <returns>
        /// The SystemNotificationEventBody instance, wrapping the provided SystemPerformanceNotificationEvent value.
        /// </returns>
        public static SystemNotificationEventBody FromSystemPerformanceNotificationEvent(SystemPerformanceNotificationEvent systemPerformanceNotificationEvent)
        {
            return new SystemPerformanceNotificationEventCase().Set(systemPerformanceNotificationEvent);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<SystemAlertNotificationEvent, T> systemAlertNotificationEvent,
            Func<SystemMaintenanceNotificationEvent, T> systemMaintenanceNotificationEvent,
            Func<SystemPerformanceNotificationEvent, T> systemPerformanceNotificationEvent);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<SystemAlertNotificationEvent, T> systemAlertNotificationEvent = null,
            Func<SystemMaintenanceNotificationEvent, T> systemMaintenanceNotificationEvent = null,
            Func<SystemPerformanceNotificationEvent, T> systemPerformanceNotificationEvent = null) =>
                Match(systemAlertNotificationEvent, systemMaintenanceNotificationEvent, systemPerformanceNotificationEvent);

        [JsonConverter(typeof(UnionTypeCaseConverter<SystemAlertNotificationEventCase, SystemAlertNotificationEvent>))]
        private sealed class SystemAlertNotificationEventCase : SystemNotificationEventBody, ICaseValue<SystemAlertNotificationEventCase, SystemAlertNotificationEvent>
        {
            public SystemAlertNotificationEvent Value;

            public override T Match<T>(
                Func<SystemAlertNotificationEvent, T> systemAlertNotificationEvent,
                Func<SystemMaintenanceNotificationEvent, T> systemMaintenanceNotificationEvent,
                Func<SystemPerformanceNotificationEvent, T> systemPerformanceNotificationEvent) =>
                   systemAlertNotificationEvent != null ? systemAlertNotificationEvent(Value) : default;

            public SystemAlertNotificationEventCase Set(SystemAlertNotificationEvent value)
            {
                Value = value;
                return this;
            }

            public SystemAlertNotificationEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<SystemMaintenanceNotificationEventCase, SystemMaintenanceNotificationEvent>))]
        private sealed class SystemMaintenanceNotificationEventCase : SystemNotificationEventBody, ICaseValue<SystemMaintenanceNotificationEventCase, SystemMaintenanceNotificationEvent>
        {
            public SystemMaintenanceNotificationEvent Value;

            public override T Match<T>(
                Func<SystemAlertNotificationEvent, T> systemAlertNotificationEvent,
                Func<SystemMaintenanceNotificationEvent, T> systemMaintenanceNotificationEvent,
                Func<SystemPerformanceNotificationEvent, T> systemPerformanceNotificationEvent) =>
                   systemMaintenanceNotificationEvent != null ? systemMaintenanceNotificationEvent(Value) : default;

            public SystemMaintenanceNotificationEventCase Set(SystemMaintenanceNotificationEvent value)
            {
                Value = value;
                return this;
            }

            public SystemMaintenanceNotificationEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<SystemPerformanceNotificationEventCase, SystemPerformanceNotificationEvent>))]
        private sealed class SystemPerformanceNotificationEventCase : SystemNotificationEventBody, ICaseValue<SystemPerformanceNotificationEventCase, SystemPerformanceNotificationEvent>
        {
            public SystemPerformanceNotificationEvent Value;

            public override T Match<T>(
                Func<SystemAlertNotificationEvent, T> systemAlertNotificationEvent,
                Func<SystemMaintenanceNotificationEvent, T> systemMaintenanceNotificationEvent,
                Func<SystemPerformanceNotificationEvent, T> systemPerformanceNotificationEvent) =>
                   systemPerformanceNotificationEvent != null ? systemPerformanceNotificationEvent(Value) : default;

            public SystemPerformanceNotificationEventCase Set(SystemPerformanceNotificationEvent value)
            {
                Value = value;
                return this;
            }

            public SystemPerformanceNotificationEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}