// <copyright file="UserNotificationEventBody.cs" company="APIMatic">
// WebhooksAndCallbacksAPI.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;

namespace WebhooksAndCallbacksAPI.Standard.Models.Containers
{
    /// <summary>
    /// This is a container class for one-of types.
    /// </summary>
    [JsonConverter(
        typeof(UnionTypeConverter<UserNotificationEventBody>),
        new[] {
            typeof(UserActionNotificationEventCase),
            typeof(UserStatusNotificationEventCase),
            typeof(UserPreferenceNotificationEventCase)
        },
        true
    )]
    public abstract class UserNotificationEventBody
    {
        /// <summary>
        /// This is UserActionNotificationEvent case.
        /// </summary>
        /// <returns>
        /// The UserNotificationEventBody instance, wrapping the provided UserActionNotificationEvent value.
        /// </returns>
        public static UserNotificationEventBody FromUserActionNotificationEvent(UserActionNotificationEvent userActionNotificationEvent)
        {
            return new UserActionNotificationEventCase().Set(userActionNotificationEvent);
        }

        /// <summary>
        /// This is UserStatusNotificationEvent case.
        /// </summary>
        /// <returns>
        /// The UserNotificationEventBody instance, wrapping the provided UserStatusNotificationEvent value.
        /// </returns>
        public static UserNotificationEventBody FromUserStatusNotificationEvent(UserStatusNotificationEvent userStatusNotificationEvent)
        {
            return new UserStatusNotificationEventCase().Set(userStatusNotificationEvent);
        }

        /// <summary>
        /// This is UserPreferenceNotificationEvent case.
        /// </summary>
        /// <returns>
        /// The UserNotificationEventBody instance, wrapping the provided UserPreferenceNotificationEvent value.
        /// </returns>
        public static UserNotificationEventBody FromUserPreferenceNotificationEvent(UserPreferenceNotificationEvent userPreferenceNotificationEvent)
        {
            return new UserPreferenceNotificationEventCase().Set(userPreferenceNotificationEvent);
        }

        /// <summary>
        /// Method to match from the provided one-of cases. Here parameters
        /// represents the callback functions for one-of type cases. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public abstract T Match<T>(
            Func<UserActionNotificationEvent, T> userActionNotificationEvent,
            Func<UserStatusNotificationEvent, T> userStatusNotificationEvent,
            Func<UserPreferenceNotificationEvent, T> userPreferenceNotificationEvent);

        /// <summary>
        /// Method to match from the provided one-of cases. The parameters represent
        /// optional callback functions for one-of type cases. You may provide only
        /// the callbacks you are interested in; others can be left as <c>null</c>. All
        /// callback functions must have the same return type T. This typeparam T
        /// represents the type that will be returned after applying the selected
        /// callback function, or the default value if no callback is provided for the matched case.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        public T MatchSome<T>(
            Func<UserActionNotificationEvent, T> userActionNotificationEvent = null,
            Func<UserStatusNotificationEvent, T> userStatusNotificationEvent = null,
            Func<UserPreferenceNotificationEvent, T> userPreferenceNotificationEvent = null) =>
                Match(userActionNotificationEvent, userStatusNotificationEvent, userPreferenceNotificationEvent);

        [JsonConverter(typeof(UnionTypeCaseConverter<UserActionNotificationEventCase, UserActionNotificationEvent>))]
        private sealed class UserActionNotificationEventCase : UserNotificationEventBody, ICaseValue<UserActionNotificationEventCase, UserActionNotificationEvent>
        {
            public UserActionNotificationEvent Value;

            public override T Match<T>(
                Func<UserActionNotificationEvent, T> userActionNotificationEvent,
                Func<UserStatusNotificationEvent, T> userStatusNotificationEvent,
                Func<UserPreferenceNotificationEvent, T> userPreferenceNotificationEvent) =>
                   userActionNotificationEvent != null ? userActionNotificationEvent(Value) : default;

            public UserActionNotificationEventCase Set(UserActionNotificationEvent value)
            {
                Value = value;
                return this;
            }

            public UserActionNotificationEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<UserStatusNotificationEventCase, UserStatusNotificationEvent>))]
        private sealed class UserStatusNotificationEventCase : UserNotificationEventBody, ICaseValue<UserStatusNotificationEventCase, UserStatusNotificationEvent>
        {
            public UserStatusNotificationEvent Value;

            public override T Match<T>(
                Func<UserActionNotificationEvent, T> userActionNotificationEvent,
                Func<UserStatusNotificationEvent, T> userStatusNotificationEvent,
                Func<UserPreferenceNotificationEvent, T> userPreferenceNotificationEvent) =>
                   userStatusNotificationEvent != null ? userStatusNotificationEvent(Value) : default;

            public UserStatusNotificationEventCase Set(UserStatusNotificationEvent value)
            {
                Value = value;
                return this;
            }

            public UserStatusNotificationEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }

        [JsonConverter(typeof(UnionTypeCaseConverter<UserPreferenceNotificationEventCase, UserPreferenceNotificationEvent>))]
        private sealed class UserPreferenceNotificationEventCase : UserNotificationEventBody, ICaseValue<UserPreferenceNotificationEventCase, UserPreferenceNotificationEvent>
        {
            public UserPreferenceNotificationEvent Value;

            public override T Match<T>(
                Func<UserActionNotificationEvent, T> userActionNotificationEvent,
                Func<UserStatusNotificationEvent, T> userStatusNotificationEvent,
                Func<UserPreferenceNotificationEvent, T> userPreferenceNotificationEvent) =>
                   userPreferenceNotificationEvent != null ? userPreferenceNotificationEvent(Value) : default;

            public UserPreferenceNotificationEventCase Set(UserPreferenceNotificationEvent value)
            {
                Value = value;
                return this;
            }

            public UserPreferenceNotificationEvent Get()
            {
                return Value;
            }

            public override string ToString()
            {
                return Value?.ToString();
            }
        }
    }
}